#! /bin/sh

#
# Monitors config
#

#Monitor sides
SECOND_MONITOR_SIDE="right"

#Get monitors
PRINCIPAL=$(xrandr | grep primary | awk '{print $1}')
SECOND_MONITOR=$(xrandr | grep connected | awk '{i++}i==2'| awk '{print $1}')

#Startup hotkey daemon
sxhkd &

#Configure Monitors
if [ "$(xrandr | grep -sw 'connected' | wc -l)" = "2" ]; then
  bspc monitor $(bspc query -M | sed -n 1p) -d I II III IV V
  bspc monitor $(bspc query -M | sed -n 2p) -d VI VII VIII IX X
  #Set Monitors Side and output 
  xrandr --output $SECOND_MONITOR --$SECOND_MONITOR_SIDE-of $PRINCIPAL
else
  bspc monitor -d I II III IV V VI VII VIII IX X 
fi


#
# Bspc flavours
#

bspc config border_width        0 
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true


#
# Bspc rules
#

bspc rule -a Code desktop='^1' follow=on
bspc rule -a Fleet desktop='^1' follow=on
bspc rule -a Obsidian dectop='^2'
bspc rule -a TelegramDesktop desktop='^10'
bspc rule -a discord desktop='^10'


#
#Starups and Setups
#

#normalize mic
amixer -D pulse sset Capture 25%

#window compositor
picom -f &

#ru-en layouts
setxkbmap -layout us,ru &

#cursor and gdk theme
xsetroot -cursor_name  left_ptr &

#wallpaper
feh --bg-max --no-fehbg /home/beaver/Images/Wallpapers/cute.jpg &

#window compositor
picom -f &

#polybar
#$HOME/.config/polybar/launch.sh &
polybar &

#notifications
dunst

#monitor config (WIP)
xrandr --output eDP-1 0.5 &

exec bspwm
